# coding: utf-8

"""
    UrbanDatasetGateway - OpenAPI 3.0

    This technical specification is one of the **Smart City Platform Specification (SCPS) for Interoperability Layer** [https://smartcityplatform.enea.it/#/en/specification/](https://smartcityplatform.enea.it/#/en/specification/)

    The version of the OpenAPI document: 1.0.0
    Contact: tito.brasolin@kerberos.energy
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from urbandatasetgateway_client.models.searching_request_request import SearchingRequestRequest

class TestSearchingRequestRequest(unittest.TestCase):
    """SearchingRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchingRequestRequest:
        """Test SearchingRequestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchingRequestRequest`
        """
        model = SearchingRequestRequest()
        if include_optional:
            return SearchingRequestRequest(
                resource_id = '',
                period_start = '',
                period_end = '',
                center_latitude = '',
                center_longitude = '',
                distance = ''
            )
        else:
            return SearchingRequestRequest(
                resource_id = '',
        )
        """

    def testSearchingRequestRequest(self):
        """Test SearchingRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
