# coding: utf-8

"""
    UrbanDatasetGateway - OpenAPI 3.0

    This technical specification is one of the **Smart City Platform Specification (SCPS) for Interoperability Layer** [https://smartcityplatform.enea.it/#/en/specification/](https://smartcityplatform.enea.it/#/en/specification/)

    The version of the OpenAPI document: 1.0.0
    Contact: tito.brasolin@kerberos.energy
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from urbandatasetgateway_client.models.deep_searching_request import DeepSearchingRequest

class TestDeepSearchingRequest(unittest.TestCase):
    """DeepSearchingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeepSearchingRequest:
        """Test DeepSearchingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeepSearchingRequest`
        """
        model = DeepSearchingRequest()
        if include_optional:
            return DeepSearchingRequest(
                resource_id = '',
                period_start = '',
                period_end = '',
                center_latitude = '',
                center_longitude = '',
                distance = '',
                property_label = '',
                property_value = ''
            )
        else:
            return DeepSearchingRequest(
                resource_id = '',
        )
        """

    def testDeepSearchingRequest(self):
        """Test DeepSearchingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
